#!/usr/bin/env php
<?php

/**
 * Script for querying data from Bags indexed in ElasticSearch.
 *
 * Run 'php bagit_searcher.php --help' for usage.
 */

require 'vendor/autoload.php';
use Elasticsearch\ClientBuilder;

$cmd = new Commando\Command();
$cmd->option('q')
  ->aka('query')
  ->describedAs('Query to perform. Do not mix with --id.');
$cmd->option('i')
  ->aka('id')
  ->describedAs('The ID of a Bag. The Elasticsearch document for the Bag will be retrieved and displayed. Do not mix with --query.')
  ->default('');
$cmd->option('a')
  ->aka('all')
  ->describedAs("List all Bags' IDs accompanied by their location.")
  ->boolean();
$cmd->option('e')
  ->aka('elasticsearch_url')
  ->describedAs('URL (including port number) of your Elasticsearch endpoint. Default is "http://localhost:9200".')
  ->default('http://localhost:9200');
$cmd->option('x')
  ->aka('elasticsearch_index')
  ->describedAs('Elasticsearch index. Default is "bags".')
  ->default('bags');

$climate = new League\CLImate\CLImate;

$hosts = array($cmd['e']);

$clientBuilder = ClientBuilder::create();
$clientBuilder->setHosts($hosts);
$client = $clientBuilder->build();

// If the request is for a all Bags, retrieve them here and go no further.
if ($cmd['all']) {
  $params = [
    'index' => 'bags',
    'type' => 'bag',
    'body' => [
        'query' => [
            'match_all' => new \stdClass(),
        ]
    ]
  ];
  $results = $client->search($params);
  foreach ($results['hits']['hits'] as $hit) {
    $table_data[] = array('Bag ID' => $hit['_id'], 'Bag Location' => $hit['_source']['bag_location']);
  }

  $climate->table($table_data);
  exit;
}

// If the request is for a specific Bag's document, retrieve it here and go no further.
if (strlen($cmd['id'])) {
  $params = [
    'index' => 'bags',
    'type' => 'bag',
    'id' => $cmd['id'],
  ];

  try {
    $response = $client->get($params);
    print_r($response);
    }
  catch (Exception $e) {
    $message = json_decode($e->getMessage());
    if (!$message->found) {
      print "Bag with ID " . $cmd['i'] . " not found.\n";
    }
    else {
      print "Oops - unanticipated error: " . $e->getMessage() . "\n";
    }
  }
  exit;
}

// Build the query.
list($field, $query) = explode(':', $cmd['q']);
switch ($field) {
  case 'content':
    $query_field = 'content';
    break;
  case 'description':
    $query_field = 'bag-info.External-Description';
    break;
  case 'date':
    $query_field = 'bag-info.Bagging-Date';
    break;
  case 'org':
    $query_field = 'bag-info.Source-Organization';
    break;
  case 'file':
    $query_field = 'data_files';
    break;
  case 'bag_location_exact':
    $query_field = 'bag_location_exact';
    break;
  case 'bag_location':
    $query_field = 'bag_location';
    break;
  case 'tombstone':
    $query_field = 'tombstone';
    break;
  default:
    print "Sorry, I don't recognize that field; you can use 'content', 'description', 'date', 'org', 'file', 'tombstone', 'bag_location_exact', or 'bag_location'." . PHP_EOL;
    exit;
}

$params = [
    'index' => 'bags',
    'type' => 'bag',
    'body' => [
        'query' => [
            'match' => array($query_field => $query),
        ]
    ]
];

// Get the results and show them to the user.
$results = $client->search($params);
if ($results['hits']['total'] > 0) {
  print "Your query found " . $results['hits']['total'] . " hit(s): " . PHP_EOL;
  $table_data = array();
  foreach ($results['hits']['hits'] as $hit) {
    switch ($field) {
      case 'content':
      $table_data[] = array('Bag ID' => $hit['_id'], 'Text content' => $hit['_source']['content']);
      break;
      case 'description':
      $table_data[] = array('Bag ID' => $hit['_id'], 'External-Description' => $hit['_source']['bag-info']['External-Description']);
      break;
    case 'date':
      $table_data[] = array('Bag ID' => $hit['_id'], 'Bagging-Date' => $hit['_source']['bag-info']['Bagging-Date']);
      break;
    case 'org':
      $table_data[] = array('Bag ID' => $hit['_id'], 'Bagging-Date' => $hit['_source']['bag-info']['Source-Organization']);
      break;
    case 'file':
      $table_data[] = array('Bag ID' => $hit['_id'], 'Data files' => implode(", ", $hit['_source']['data_files']));
      break;
    case 'bag_location_exact':
      $table_data[] = array('Bag ID' => $hit['_id'], 'Source path' => $hit['_source']['bag_location_exact']);
      break;
    case 'bag_location':
      $table_data[] = array('Bag ID' => $hit['_id'], 'Source path' => $hit['_source']['bag_location']);
      break;
    case 'tombstone':
      $table_data[] = array('Bag ID' => $hit['_id'], 'Tombstone' => $hit['_source']['tombstone']);
      break;
    }
  }
  $climate->table($table_data);
}
else {
  print "Your query found no hits. Sorry." . PHP_EOL;
}

